# -*- coding: utf-8 -*-
"""Laboratorio18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtL6twQ6MlhBJDNLuDdu289wcyUY4wDq
"""

nombre=input("Ingrese su nombre:")
edad=int(input("Ingrese su edad: "))
estatura=float(input("Ingrese su estatura en metros: "))
esEstudiante=True
print(f"nombre: {nombre} edad {edad} estatura: {estatura} estudiante: {esEstudiante}")



"""Ejercicio 2"""

import math as m
num1=int(input("Ingrese un numero: "))
num2=int(input("Ingrese un numero: "))
sumar=num1+num2
restar=num1-num2
multiplicar=num1*num2
dividir=num1/num2
potencia2=m.pow(num1,num2)
potencia2=num1**num2
print(f"La suma de los numeros es: {sumar}")
print(f"La resta de los numeros es: {restar}")
print(f"La multiplicacion de los numeros es: {multiplicar}")
print(f"La division de los numeros es: {dividir}")
print(f"La potencia de los numeros es: {potencia2}")
print(f"La potencia de los numeros es: {potencia2}")

"""Ejercicio 3"""

78
texto1=input("Ingrese frase 1:")
texto2=input("Ingrese frase 2:")
print(f"{texto1} {texto2}")
if texto1==texto2:
    print("Las frases son iguales")
else:
    print("Las frases son diferentes")

"""Ejercicio 4"""

Lista=[] #Definicion de una lista vacia

#2 Ingreso de datos a la lista

for i in range(5):
    numero=int(input("Ingrese un numero: "))
    Lista.append(numero)
print(Lista)

#3 Modificacion de un elemento

Lista[4]="cambio de informacion"
print(f"Lista modificada: {Lista}")

#4 Agregar elemento e imprimir
Lista.append("nuevo dato")
print(f"Lista con campo nuevo: {Lista}")

#5 Eliminar un elemento nuevo
Lista.remove("nuevo dato")
print(f"Lista con campo eliminado: {Lista}")