# -*- coding: utf-8 -*-
"""Laboratorio19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OtL-CsTjCgIgtoh5T0lNHjG85CGEYgYQ
"""



"""  Ejercicio Condicionales
  Parte 1
"""

num=int(input("Ingresa un número: "))
if num%2==0:
    print(f"El número {num} es par")
else:
    print(f"El número {num} es impar")

"""Parte b"""

num=int(input("Ingresa un número positivo de uno, dos o tres digitos "))
if num>0 and num<=9:
    print(f"El número {num} tiene un dígito")
elif num>9 and num<=99:
    print(f"El número {num} tiene dos dígitos")
elif num<=999:
    print(f"El número {num} tiene tres dígitos")
else:
    print(f"El número {num} está fuera del rango permitido")

"""Parte 2"""



Empleados_bajo_3000000 = 0
Empleados_alto_3000000 = 0
totalGastos = 0

x = 1
n=int(input("Ingrese el número de empleados: "))
while x <= n:
    sueldo = float(input(f"Ingrese el sueldo del empleado: "))
    if sueldo>1000000 and sueldo<=3000000:
      Empleados_bajo_3000000 = Empleados_bajo_3000000 + 1
    else:
      Empleados_alto_3000000 = Empleados_alto_3000000 + 1
    totalGastos = totalGastos + sueldo
    x = x + 1
    print(f"El número de empleados con sueldo bajo de 3 millones es: {Empleados_bajo_3000000}")
    print(f"El número de empleados con sueldo alto de 3 millones es: {Empleados_alto_3000000}")
    print(f"El total de gastos es: {totalGastos}")

"""Parte b"""

cuadrante1 = 0
cuadrante2 = 0
cuadrante3 = 0
cuadrante4 = 0
x = 1
n=int(input("Ingrese el número de puntos: "))
for x in range(n):
    x1 = int(input("Ingrese la coordenada x: "))
    y1 = int(input("Ingrese la coordenada y: "))
    if x1 > 0 and y1 > 0:
        cuadrante1 = cuadrante1 + 1
        print(f"El punto ({x1},{y1}) pertenece al cuadrante 1")
        print(f"El número de puntos en el cuadrante 1 es: {cuadrante1}")
    elif x1 < 0 and y1 > 0:
        cuadrante2 = cuadrante2 + 1
        print(f"El punto ({x1},{y1}) pertenece al cuadrante 2")
        print(f"El número de puntos en el cuadrante 2 es: {cuadrante2}")
    elif x1 < 0 and y1 < 0:
        cuadrante3 = cuadrante3 + 1
        print(f"El punto ({x1},{y1}) pertenece al cuadrante 3")
        print(f"El número de puntos en el cuadrante 3 es: {cuadrante3}")
    else:
        cuadrante4 = cuadrante4 + 1
        print(f"El punto ({x1},{y1}) pertenece al cuadrante 4")
        print(f"El número de puntos en el cuadrante 4 es: {cuadrante4}")